channels:
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - matplotlib-base=3.8.2
  - matplotlib-inline=0.1.6
  - numpy=1.26.3
  - osmnx=1.8.1
  - pandas=2.1.4
  - plotly=5.18.0
  - pyarrow=14.0.2
  - scikit-learn=1.3.2
  - geopandas=0.14.2
  - osmium-tools=1.16.0
  - osmnx=1.8.1